### ISSUE TITLE
Wondering if the pretrained weights are available

### ISSUE THREAD

**Issue by waaaaangchangwen** [liuyoude/STgram-MFN#11]
Hi, I'm currently trying to recreate your on result on the development set, however even if I use the same setting as the config.yaml, the results are still slightly worse (about 3-5%, different on different machine type) than the results on the paper. I'm wondering if it's possible for you to provide the pretrained weights as a reference. Thanks!

**Comment by liuyoude** [comment]
the model weights can be get in [stgram-mfn-weights](https://zenodo.org/record/7194640#.Y0gucXZBxD8)

**Comment by waaaaangchangwen** [comment]
Thanks for the help!
