### ISSUE TITLE
An error occurs during validation datasets

### ISSUE THREAD

**Issue by Peter-SungwooCho** [liuyoude/STgram-MFN#16]
```
    def forward(self, x):
        
        # print(x.shape) # torch.Size([1, 1, 160000]) -> torch.Size([1, 1, 131050])
        # print('#'*20)
        out = self.conv_extrctor(x)
        # print(out.shape) # torch.Size([1, 128, 313]) -> torch.Size([1, 128, 256])
        out = self.conv_encoder(out)
        return out
```

In the process of validation, it was confirmed that some of the data for each machine id was not validated as the size of the torch changed. Is there any solution? The code is the forward part of Tgramnet.

**Comment by liuyoude** [comment]
It may because the length of each audio is different, one possible strategy is to cut them all to the same length：[code](https://github.com/liuyoude/STgram-MFN/blob/d6c886559ed3d2f0ff3e35b289d391addcedbd7d/dataset.py#L28) . In the dataset we use, the audios are all about 10s, so we cut them to 10s.

**Comment by Peter-SungwooCho** [comment]
I used the code as it is, but the same problem occurs. What is the reason?

**Comment by liuyoude** [comment]
if the sample rate is 16k hz, torch.Size([1, 1, 131050]) shows the length of audio < 10s，it may be padded to the same length, or cut to same length

**Comment by Peter-SungwooCho** [comment]
Thank you. There was a problem with the dataset itself. I found the dataset and inserted it normally, and it worked!
