### ISSUE TITLE
Why is the frame number 313？

### ISSUE THREAD

**Issue by WLBRich** [liuyoude/STgram-MFN#4]
Why is the frame number 313？

**Comment by liuyoude** [comment]
It is calculated by 10 seconds and 16kHz audio with 1024 window length and 512 hop length. The torchaudio is used to extract the log-Mel spectrogram. The frame number should change if these parameters mentioned above change.

**Comment by WLBRich** [comment]
> It is calculated by 10 seconds and 16kHz audio with 1024 window length and 512 hop length. The torchaudio is used to extract the log-Mel spectrogram. The frame number should change if these parameters mentioned above change.

Thanks for your reply!
I am trying to migrate this project, but I am confused why num_class = 41, why not 6?
