### ISSUE TITLE
why num_class = 41, why not 6?

### ISSUE THREAD

**Issue by WLBRich** [liuyoude/STgram-MFN#5]
Thanks for your reply!
I am trying to migrate this project, but I am confused why num_class = 41, why not 6?

**Comment by liuyoude** [comment]
Because the machine IDs is used as the classification labels, not machine types. Each machine type has 6 to 7 machine IDs in the development and additional dataset of DCASE2020 Task2.

**Comment by WLBRich** [comment]
> Because the machine IDs is used as the classification labels, not machine types. Each machine type has 6 to 7 machine IDs in the development and additional dataset of DCASE2020 Task2.

According to your results，every machine type has 4 machine IDs

**Comment by liuyoude** [comment]
> > Because the machine IDs is used as the classification labels, not machine types. Each machine type has 6 to 7 machine IDs in the development and additional dataset of DCASE2020 Task2.
> 
> According to your results，every machine type has 4 machine IDs

Because it's the results of test data in development dataset. The other machine IDs is in the additional dataset. The information about dataset can be seen in the README.

**Comment by WLBRich** [comment]
> > > Because the machine IDs is used as the classification labels, not machine types. Each machine type has 6 to 7 machine IDs in the development and additional dataset of DCASE2020 Task2.
> > 
> > 
> > According to your results，every machine type has 4 machine IDs
> 
> Because it's the results of test data in development dataset. The other machine IDs is in the additional dataset. The information about dataset can be seen in the README.

I see. Thank you vrey much!

**Comment by WLBRich** [comment]
As you can see above，is there something need to send http request? I get something wrong about this.

**Comment by WLBRich** [comment]
> As you can see above，is there something need to send http request? I get something wrong about this.

As you can see above，is there something need to send http request? I get somethin

As you can see above，is there something need to send http request? I get something wrong about this.

**Comment by liuyoude** [comment]
> Thanks for your reply! I am trying to migrate this project, but I am confused why num_class = 41, why not 6?

There are 7 IDs for Fan, Slider, Valve, Pump and ToyCar and 6 IDs for ToyConveyor. So total classes are 41.
